// AUTH
export const UPDATE_AUTH = 'UPDATE_AUTH';

// USER
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

// COLLECTIONS
export const COLLECTION_ERROR = 'COLLECTION_ERROR';
export const LOAD_DOCUMENTS = 'LOAD_DOCUMENTS';
