// AUTH
export const UPDATE_AUTH = 'UPDATE_AUTH';

// USER
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

// COLLECTIONS
export const COLLECTION_ERROR = 'COLLECTION_ERROR';
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_RESULTS = 'LOAD_RESULTS';
export const CLEAR_QUIZZES = 'CLEAR_QUIZZES';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const SAVING_COMPLETE = 'SAVING_COMPLETE';
